# Generated by Django 5.0.6 on 2024-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='created'),
        ),
        migrations.AlterField(
            model_name='section',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
