# Generated by Django 5.0.6 on 2024-05-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='img_width',
        ),
    ]
