# Generated by Django 5.0.6 on 2024-05-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_slug_alter_section_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='section',
            name='img_width',
        ),
    ]
