# Generated by Django 5.0.6 on 2024-05-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_section_img_height_remove_section_img_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='bodytext',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
